trigger:
  branches:
    include:
      - main

jobs:
  - job: BuildAndTest
    displayName: 'Build and Test'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self
      - script: |
          # Build commands
          npm install
          npm run build

      - script: |
          # Test commands
          npm run test

  - job: Deploy
    displayName: 'Deploy to Azure Kubernetes Service'
    dependsOn: BuildAndTest
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          # Deployment commands
          az login --service-principal -u $(AzureServicePrincipalId) -p $(AzureServicePrincipalPassword) --tenant $(AzureTenantId)
          az aks get-credentials --resource-group $(ResourceGroupName) --name $(AksClusterName)
          kubectl apply -f deployment.yaml
